README.md, cmd/changelog-parser/main.go, pkg/http/http.go, pkg/http/http_test.go
This will make use of the tool much easier and less likely to end in info disclosure when we reach the low unauthenticated API limit.
Issue: #52
=> 52 Add API CLI token support

pkg/changelog/parse.go, pkg/changelog/parse_test.go, pkg/changelog/testdata/changelog.simple.md
Each leaf node's textual representation must be implemented in the parser. In the meantime, any leaf node without an implementation will just be represented as plaintext
=> Markdown parser renders unimplemented leaf nodes as plaintext

.github/workflows/release.yml, CONTRIBUTING.md
This change allows our pipeline to auto-run when a new tag is pushed,
ensuring that no manual action is needed other than publishing the
release is needed when we are cutting a release. We currently attach
only the release notes and changelog markdown notes to the release but
there may be more changes that we want later.
=> 38 Add auto-generation of a draft prerelease when a `v*` tag is pushed

cmd/changelog-parser/testdata/expected_release_output.txt, templates/RELEASE_NOTES_unified.md.tmpl, templates/testdata/RELEASE_NOTES_unified.md
This adds a ToC and component version listing to the release notes. This does not de-duplicate versions from the same repository yet though which will be handled in the follow-up work.
As part of these changes, improvements were made to the listing of the changeset brevity as well.
Issue #61
=> 61 Add component versions to release notes

cmd/changelog-parser/main.go, cmd/changelog-parser/testdata/expected_release_output.txt, pkg/repositories/repositories.go, pkg/repositories/repositories_test.go, pkg/template/template.go, templates/RELEASE_NOTES_unified.md.tmpl, templates/templates_test.go, templates/testdata/RELEASE_NOTES_unified.md
To support this change, the layout of our data was changed so that we
have per-component hierarchy rather than per-changelog so that we can
enumerate releases as well as only show the latest one per component in
the templates.
=> Made release notes output only link to latest component release

cmd/changelog-parser/main.go, cmd/changelog-parser/testdata/expected_release_output.txt, cmd/changelog-parser/testdata/repositories.yml, pkg/repositories/repositories.go, pkg/repositories/repositories_test.go, pkg/repositories/testdata/repositories.yml, pkg/template/template.go, repositories.yml, templates/RELEASE_NOTES_unified.md.tmpl, templates/templates_test.go, templates/testdata/RELEASE_NOTES_unified.md
This PR adds any upgrade instructions to the generated release notes. Minor adjustment was made to readability of release notes to make the components easier to visually parse too.
=> 68 Add upgrade instructions to release notes

cmd/changelog-parser/main.go, pkg/repositories/repositories.go, pkg/repositories/repositories_test.go, pkg/repositories/testdata/repositories_current.yml, pkg/repositories/testdata/repositories_new.yml
- If a secondary repository.yml file is passed in,
we extract the repositories from the new (secondary) repository.yml
to compare against the current (first) repository.yml
- If a repository in the current file is also in the new file, based on
having identical URLs, we set the version of the current repository data
to the new version in the new file
=> Add version diffing for multiple repository files

README.md, cmd/changelog-parser/main.go
This change fixes the issue with exceeding the quota while running test cases. The GITHUB_TOKEN envvar is also the standard across multiple Github tools.
=> Ability to specify Github token as GITHUB_TOKEN environment variable

repositories.yml
To enable testing of the suite release processes, we're updating the suite release YAML
to include the basic set of projects we expect might be included, and marking them all
to be at a version one below their latest
Note - the final suite release may include different versions of tools and a different set of
tools entirely - this draft file should not be taken as the plan for the official release
Each entry in this YAML should have a `version` and a `certification`.
=> Adding test 0.0.0 suite release versions to YAML

cmd/changelog-parser/testdata/expected_release_output.md, pkg/template/template.go, templates/RELEASE_NOTES_unified.md.tmpl, templates/testdata/RELEASE_NOTES_unified.md
- Added repo-name headers for each version list in the 'changes'
section
- Added a table of contents to the 'changes' section, linking to the
repo-name headers
- Changes the added, removed, etc. subheaders to use bullets instead,
to improve readability at a glance
=> 62 Improve Release Notes visual representation

.github/workflows/draft-release.yml, .github/workflows/e2e-tests.yml, .github/workflows/release-publish-suite-commit.yml, .github/workflows/unit-tests.yml
Included here:
- Action `release` -> `draft-release`
- Action `test` -> `unit-tests`
- Action `release-test` -> `e2e-tests`
- Fixed issues with `release` action logic paths
- Made E2E tests run on PRs and master branch only
- Made job/action naming consistent
=> Fixup action naming and logic

.github/workflows/release-publish-suite-commit.yml, .github/workflows/update-suite-release-pr.yml
Since master is protected, this change will allow us to auto-open a PR with those changes from a separate branch.
=> On post-release workflow, open a PR instead of pushing to master

.github/workflows/draft-release.yml
The variables that ended up in the output of draft release GitHub
actions were the full refs but we needed to use just the trimmed down
version name. This change implements that change.
=> Fix draft release version variables

.github/workflows/draft-release.yml
Env vars do not carry over between jobs so we need another re-definition
of GIT_BRANCH variable to be able to get the right variable.
=> Fix generation of version in suite draft release action

.github/workflows/e2e-tests.yml, cmd/changelog-parser/main.go, cmd/changelog-parser/main_test.go, pkg/github/github.go, pkg/http/http.go, pkg/log/log.go, pkg/repositories/repositories.go, pkg/template/template.go, release-testing/kv/cmd/main.go, release-testing/kv/store.go, release-testing/policy.yml.sh, release-testing/prepare.sh, release-testing/secretless_test.go, release-testing/store-component-versions.go, release-testing/store.sh, release-testing/test
Using some redirection it's possible to selectively log steps in the release test scripts. This makes it possible to have info logs on stdout and debug logs on file. The debug logs can be consulted on failure.
=> Logging levels for E2E tests

cmd/changelog-parser/main_test.go
Old code would silently eat the errors but now we ensure that we check
and print the errors if they happen.
=> Added error checking to `cli.RunParser` tests of main.go

.github/workflows/e2e-tests.yml
The helm version needs to be prefixed with a 'v'.
=> fix: Helm version in e2e-tests workflow

.github/workflows/unit-tests.yml
This avoids the API rate limit exceeded error from the Github API
=> Update unit-tests workflow to use GITHUB_TOKEN

pkg/cli/testdata/expected_docs-release_output.txt, pkg/template/template.go, pkg/template/template_test.go, templates/RELEASE_NOTES_unified.htm.tmpl
If a markdown-type link is found in a changelog list item, it
is replaced with an HTML anchor
- Introduced a new function map function for the template
generator, called markdownHyperlinksToHTMLHyperlinks
- Added unit test for markdownHyperlinksToHTMLHyperlinks
- Updated test output for docs-release testing
=> 112 - HTML Template Output Converts Markdown Tags to HTML Anchors

pkg/github/github.go, pkg/version/version.go, pkg/version/version_test.go
We now tied the "semver" latest release resolution into the main code to replace
the temporal-based latest release version resolution.
Connected to #133
=> 133 `latest` release resolution fix

pkg/github/github.go, pkg/github/github_test.go, pkg/github/testdata/compare_v3.json, pkg/version/version.go, pkg/version/version_test.go, templates/UNRELEASED_CHANGES_unified.md.tmpl, templates/templates_test.go, templates/testdata/UNRELEASED_CHANGES_unified.md
This link is conditionally added immediately after the latest version tag. The condition is if there are new commits beyond the latest version tag.
See this test example for how the report looks. Look for `cyberark/conjur @HEAD`. https://github.com/cyberark/conjur-oss-suite-release/blob/unreleased-changes/templates/testdata/UNRELEASED_CHANGES_unified.md
=> Unreleased Report: Include links to unreleased changes at HEAD

pkg/cli/cli_test.go, pkg/cli/testdata/expected_changelog_diff_output.txt, pkg/cli/testdata/expected_docs-release_diff_output.txt, pkg/cli/testdata/expected_docs-release_output.txt, pkg/cli/testdata/expected_release_diff_output.txt, templates/RELEASE_NOTES_unified.htm.tmpl, templates/RELEASE_NOTES_unified.md.tmpl, templates/testdata/RELEASE_NOTES_unified.htm
- Tests added for when we run diffing against two suites,
and a repo version has not changed. In this case, we do not
write the change notes for that unchanged version. Test data
added that reflects that scenario.
- Updated templates to not create a header for categories without
any changes
=> 140 - Update templates to ignore empty changelogs

CONTRIBUTING.md
Update CONTRIBUTING.md with step-by-step instructions for
creating a new release, with links to relevant resources, project
pages, and workflow documentation.
Connected to cyberark/community#47
=> Add complete release instructions to CONTRIBUTING

.github/workflows/e2e-tests.yml, pkg/cli/testdata/expected_changelog_output.txt, pkg/cli/testdata/expected_docs-release_output.txt, pkg/cli/testdata/expected_release_diff_output.txt, pkg/cli/testdata/expected_release_output.txt, pkg/cli/testdata/suite.yml, releases/suite_0.0.0.yml, suite.yml, templates/RELEASE_NOTES_unified.md.tmpl, templates/partials/certification_badge.md, templates/partials/testdata/certification_badge_certified.md, templates/partials/testdata/certification_badge_community.md, templates/partials/testdata/certification_badge_trusted.md, templates/partials/testdata/certification_badge_unknown.md, templates/testdata/RELEASE_NOTES_unified.md
- Clean up the dev 0.0.0 release in preparation for tagging an actual baseline 0.0.1 release
- Bump the versions in the suite.yml to be consistent with where projects were as of the DAP 11.4 RC build on April 2
- Edit the default certification level colors to the values we plan to use, and update the code to not print CL info if the level is unknown
=> Clean up dev release to prepare for 0.0.1 baseline release

.github/workflows/e2e-tests.yml, k8s-ci/Dockerfile, release-testing/prepare.sh
The postgresql helm chart has been depracted from the stable repository and moved to the bitnami repository. This commit makes the relevant changes.
=> Update postgresql helm chart to pull from bitnami repository

.github/workflows/draft-release.yml
Many steps in the draft release workflow interacted with the GH API but did
not use the GH token, so the flow was failing very quickly. This commit updates
the workflow to add the GITHUB_TOKEN env var to all of the relevant steps.
=> Update draft release to use GH token for steps

suite.yml
Repos with changes on master that we are not including in this version, since both require a fair amount of manual testing before we can tag, and we don't want to block the release:
- Summon
- Python3
I also removed Google cloud marketplace from this initial suite release - the project isn't ready yet with a published version that uses the suite Conjur version, so rather than have it block the release, we have removed it for now.
=> Updating suite.yml for 1.5.0+suite.1 release

pkg/github/github.go, pkg/version/version.go, pkg/version/version_test.go
Old code would assume that a missing upper or lower bound should be
treated the same but effectively they have different meanings:
- Missing lower bound should just return current high bound
- Missing upper bound should be used like a normal comparison baseline
which may not return a result
This change should fix the resulting output of unreleased changes while
having no effect on other outputs.
Connected to #154
=> Fixed clipping of unbounded upper releases version numbers

pkg/cli/testdata/expected_docs-release_diff_output.txt, pkg/cli/testdata/expected_docs-release_output.txt, pkg/cli/testdata/expected_release_diff_output.txt, pkg/cli/testdata/expected_release_output.txt, templates/RELEASE_NOTES_unified.htm.tmpl, templates/partials/conjur_installation_instructions.md, templates/templates_test.go, templates/testdata/RELEASE_NOTES_unified.htm, templates/testdata/RELEASE_NOTES_unified.md, templates/testdata/UNRELEASED_CHANGES_unified.md
This change adds installation instructions to generated `docs-release`
artifacts as they are needed there for our users. This change also removes out
AMI-specific update instructions from all templates as we don't maintain those
anymore.
=> 169 Add install instructions to html docs

suite.yml
Adds a link in the suite.yml to the helm upgrade instructions
Note: I manually generated the `v1.5.0+suite.1` HTML release notes with this change included and submitted them to be published in the docs, since I think including this link adds value. I confirmed that the diff between the HTM notes attached to the GH release and this new version is just these lines:
```
<li>
<p><a href="https://github.com/cyberark/conjur-oss-helm-chart/tree/master/conjur-oss#upgrading-modifying-or-migrating-a-conjur-oss-helm-deployment ">cyberark/conjur-oss-helm-chart</a></p>
</li>
```
n/a
=> Add helm chart upgrade URL

pkg/changelog/parse_test.go, pkg/changelog/testdata/changelog.complex.md, pkg/cli/testdata/expected_changelog_diff_output.txt, pkg/cli/testdata/expected_changelog_output.txt, pkg/cli/testdata/expected_docs-release_diff_output.txt, pkg/cli/testdata/expected_docs-release_output.txt, pkg/cli/testdata/expected_release_diff_output.txt, pkg/cli/testdata/expected_release_output.txt
Our static expected test data was outdated,
due to retroactive changes to the Conjur
CHANGELOG.md. This change adjusts the wording
to accurately reflect expected output.
Resolves #186
=> Fix failing unit tests

pkg/cli/cli.go, pkg/cli/testdata/expected_docs-release_diff_output.txt, pkg/cli/testdata/expected_docs-release_output.txt, pkg/cli/testdata/new_release_suite.yml, pkg/cli/testdata/suite.yml, pkg/repositories/repositories.go, pkg/repositories/repositories_test.go, pkg/template/template.go, templates/RELEASE_NOTES_unified.htm.tmpl, templates/templates_test.go, templates/testdata/RELEASE_NOTES_unified.htm
- Updates HTML release note template to match v1.5.0+suite.1
- In v1.5.0+suite.1, some minor tweaks were made to the release notes that we
didn't backport to the automation. In this commit, we update the HTML release
notes (and relevant test output) to ensure the auto-generated HTML we create
this time includes these fixes.
- Adds suite description to HTML release notes output, so that each release will include
the release-specific description in the release docs. 
Resolves #191
=> Update HTML release notes

k8s-ci/Dockerfile
The new stable Debian version is buster, so this Dockerfile needs to be updated accordingly. Without this change the Jenkins pipeline will fail.
Related to #196 - the Go 1.15 version bump means we needed to change the Debian base of the Go image we use
=> Change test Docker Go image from stretch to buster

CHANGELOG.md, pkg/cli/testdata/expected_changelog_output.txt, pkg/cli/testdata/expected_docs-release_diff_output.txt, pkg/cli/testdata/expected_docs-release_output.txt, pkg/cli/testdata/expected_release_output.txt, pkg/template/template.go, pkg/template/template_test.go, templates/RELEASE_NOTES_unified.htm.tmpl, templates/templates_test.go, templates/testdata/RELEASE_NOTES_unified.htm, templates/testdata/RELEASE_NOTES_unified.md, templates/testdata/UNRELEASED_CHANGES_unified.md
Updates all relevant tests, including amending existing tests to verify that the
docs links are exempted and don't open in a new window.
Also fixes issue in CLI tests due to change made in actual python3 changelog.
Note: the upgrade instruction links all open in a new window, even though some of them are docs links. This is still a marked improvement from the current state, where every link needs to be hand-updated to add `target="_blank"` - now, just one or two links will need an update. When the helm chart docs are migrated to Flare, all upgrade links will point to docs sites and the `target="_blank"` additions in this section can be removed at that time. 
Resolves #199 …
=> Update HTML links to open in a new window

CHANGELOG.md, CONTRIBUTING.md, suite.yml
- Preps for v1.11.1+suite.1 release
- Fixes test failure that came from a change to real release notes
Resolves #194 
Release checklist: https://github.com/cyberark/conjur-oss-suite-release/wiki/v1.11.1-suite.1
Draft release notes: https://gist.github.com/izgeri/0a60f26246decfdcac8fe1c5e3856abf
Early draft of docs output: [ConjurSuite.htm.zip](https://github.com/cyberark/conjur-oss-suite-release/files/5637762/ConjurSuite.htm.zip) - ~would like to resolve #199 before creating actual docs HTML~ - there is one manual change required to the docs link in the upgrade instructions section (so it won't pop up in a new window).
```
summon -p keyring.py …
```
=> Update suite.yml for v1.11.1+suite.1

.gitignore, CHANGELOG.md, bin/Dockerfile, bin/test_unit, pkg/version/version.go, pkg/version/version_test.go
Our parsing for versions didn't account for the
"+suite.x" syntax, but now performs a
comparison on the suite number in the event
that two releases have the same semver.
Also adds a `bin/test_unit` script for local development work
Resolves #208 
```
-t release
```
=> Version parsing supports suite versioning

.github/workflows/draft-release.yml, .github/workflows/unit-tests.yml, CHANGELOG.md
On the v1.11.2+suite.1 release we discovered that the draft-release workflow
was not correctly determining the version from the GITHUB_REFS env var. This
commit updates the logic to determine the version so that this will work
correctly on the next release.
Also removes unneeded version parsing from unit test flow.
Resolves #212
```
-t release
```
=> Update strategy for determining tag version

CHANGELOG.md, suite.yml
Wiki page: https://github.com/cyberark/conjur-oss-suite-release/wiki/v1.11.3-suite.1
[ZenHub board with release issues](https://app.zenhub.com/workspaces/community-and-integrations-team-5e28ab8f700a191286d5abe0/board?releases=603404b707df71be02ba7c04&repos=62174977,107414536,35568823,13068807,181756824,169479430,151117144,114040729,131041551,155729153,144302471,24191248,129415225,121428226,127067545,131177218,87459360,128110795,38008676,112209945,7396760,7396761,142046583,132513819,37145674,110738790,35956445,129148193,46360727,167067005,181513803,175443058,140766424,149802600,165913758,202615062,124427370,112222188,206022444,181930446,180458470,52056584,133858256,170183803,42073272,36090509,217348257,236054196,142932883,218336465,241929531,248887016,239805656,269868540,320296980)
Draft …
=> Prepare for v1.11.3+suite.1 release

CHANGELOG.md, suite.yml
Updates Conjur, Helm chart, Python SDK
Release wiki page: https://github.com/cyberark/conjur-oss-suite-release/wiki/v1.11.5-suite.1
Draft release notes: https://gist.github.com/izgeri/f3004554c1c7c3523a642b63dab7a026
[ZenHub board](https://app.zenhub.com/workspaces/community-and-integrations-team-5e28ab8f700a191286d5abe0/board?releases=60632a8e46544061ee7e463a&repos=62174977,107414536,35568823,13068807,181756824,169479430,151117144,114040729,131041551,155729153,144302471,24191248,129415225,121428226,127067545,131177218,87459360,128110795,38008676,112209945,7396760,7396761,142046583,132513819,37145674,110738790,35956445,129148193,46360727,167067005,181513803,175443058,140766424,149802600,165913758,202615062,124427370,112222188,206022444,181930446,180458470,52056584,133858256,170183803,42073 …
=> Bump version v1.11.5+suite.1

CONTRIBUTING.md, README.md, pkg/cli/testdata/expected_release_diff_output.txt, pkg/cli/testdata/expected_release_output.txt, templates/partials/conjur_installation_instructions.md, templates/testdata/RELEASE_NOTES_unified.md
Updating naming for Conjur editions
- converts `Conjur OSS` to `Conjur Open Source`
- converts `DAP`/`Dynamic Access Provider` to `Conjur Enterprise`
- maintains `Conjur OSS Suite` and `Conjur Open Source Suite`
This is part of an automated batch of PRs across many repos listed in [cyberark/community#92](https://github.com/cyberark/community/issues/92)
=> Updating naming for Conjur editions

CHANGELOG.md, suite.yml
- **[cyberark/conjur v1.11.7](https://github.com/cyberark/conjur/releases/tag/v1.11.7)** (2021-06-08)
- **[cyberark/conjur-openapi-spec v5.1.1](https://github.com/cyberark/conjur-openapi-spec/releases/tag/v5.1.1)** (2021-04-28)
- **[cyberark/conjur-oss-helm-chart v2.0.4](https://github.com/cyberark/conjur-oss-helm-chart/releases/tag/v2.0.4)** (2021-04-12) …
=> Update suite.yml for v1.11.7+suite.1 release

CHANGELOG.md, suite.yml
- **[cyberark/conjur v1.13.1](https://github.com/cyberark/conjur/releases/tag/v1.13.1)** (2021-09-13) 
- **[cyberark/conjur-openapi-spec v5.2.0](https://github.com/cyberark/conjur-openapi-spec/releases/tag/v5.2.0)** (2021-09-08) 
- **[cyberark/conjur-oss-helm-chart v2.0.4](https://github.com/cyberark/conjur-oss-helm-chart/releases/tag/v2.0.4)** (2021-04-12)  …
=> Update suite.yml for v1.13.1+suite.1 release

CHANGELOG.md, suite.yml
- **[cyberark/conjur v1.14.1](https://github.com/cyberark/conjur/releases/tag/v1.14.1)** (2021-11-05) 
- **[cyberark/conjur-openapi-spec v5.2.0](https://github.com/cyberark/conjur-openapi-spec/releases/tag/v5.2.0)** (2021-09-08) 
- **[cyberark/conjur-oss-helm-chart v2.0.4](https://github.com/cyberark/conjur-oss-helm-chart/releases/tag/v2.0.4)** (2021-04-12)  …
=> Bump version for v1.14.1+suite.1 release

pkg/cli/cli.go
A warning serves the dual purpose of informing the user of the possibility of specifying the Github API token, and anticipating a likely failure mode
Example logs:
```
@doodlesbykumbi ➜ /workspaces/conjur-oss-suite-release (main ✗) $ ./parse-changelogs -v v1.14.1+suite.1 -t release -o RELEASE_NOTES.md
2021/11/15 21:10:19 Starting changelog parser...
2021/11/15 21:10:19 Parsing linked repositories...
2021/11/15 21:10:19 Reading suite.yml...
2021/11/15 21:10:19 Unmarshaling data...
2021/11/15 21:10:19 Releases dir: releases
2021/11/15 21:10:19 Using releases/suite_1.13.1+suite.1.yml as previous release for pinning
2021/11/15 21:10:19 Reading releases/suite_1.13.1+suite.1.yml...
2021/11/15 21:10:19 Unmarshaling data...
2021/11/15 21:10:19 Collecting changelogs...
2021/11/15 21:10:19 WARN: No …
```
=> Log warning message when no Github API token is specified

suite.yml
- **[cyberark/conjur v1.15.0](https://github.com/cyberark/conjur/releases/tag/v1.15.0)** (2021-12-21) 
- **[cyberark/conjur-openapi-spec v5.2.0](https://github.com/cyberark/conjur-openapi-spec/releases/tag/v5.2.0)** (2021-09-08) 
- **[cyberark/conjur-oss-helm-chart v2.0.4](https://github.com/cyberark/conjur-oss-helm-chart/releases/tag/v2.0.4)** (2021-04-12)  …
=> Release v1.15.0+suite.1

CHANGELOG.md, suite.yml
- **[cyberark/conjur v1.17.6](https://github.com/cyberark/conjur/releases/tag/v1.17.6)** (2022-04-07) 
- **[cyberark/conjur-openapi-spec v5.3.0](https://github.com/cyberark/conjur-openapi-spec/releases/tag/v5.3.0)** (2021-12-22) 
- **[cyberark/conjur-oss-helm-chart v2.0.4](https://github.com/cyberark/conjur-oss-helm-chart/releases/tag/v2.0.4)** (2021-04-12)  …
=> Update suite.yml for v1.17.6+suite.1 release

CHANGELOG.md, suite.yml
- **[cyberark/conjur v1.18.0](https://github.com/cyberark/conjur/releases/tag/v1.18.0)** (2022-08-01) 
- **[cyberark/conjur-openapi-spec v5.3.0](https://github.com/cyberark/conjur-openapi-spec/releases/tag/v5.3.0)** (2021-12-22) 
- **[cyberark/conjur-oss-helm-chart v2.0.5](https://github.com/cyberark/conjur-oss-helm-chart/releases/tag/v2.0.5)** (2022-08-17)  …
=> Update suite.yml for v18.0.0+suite1 release

CHANGELOG.md, suite.yml
- **[cyberark/conjur v1.18.4](https://github.com/cyberark/conjur/releases/tag/v1.18.4)** (2022-09-11) 
- **[cyberark/conjur-openapi-spec v5.3.0](https://github.com/cyberark/conjur-openapi-spec/releases/tag/v5.3.0)** (2021-12-22) 
- **[cyberark/conjur-oss-helm-chart v2.0.5](https://github.com/cyberark/conjur-oss-helm-chart/releases/tag/v2.0.5)** (2022-08-17)  …
=> Update suite.yml for v1.18.4+suite.1 release

release-testing/prepare.sh
CI is failing due to `error: unknown flag --generator`. [This was deprecated in from the `kubectl run`](https://github.com/kubernetes/kubernetes/pull/87077) command, which now only supports creating pods - all other generators were moved under `kubectl create`.
Remove the --generator flag from `kubectl run`
*At least 1 todo must be completed in the sections below for the PR to be
merged.*
CHANGELOG update
changes, or
=> Remove --generator tag

CHANGELOG.md, suite.yml
- **[cyberark/conjur v1.19.0](https://github.com/cyberark/conjur/releases/tag/v1.19.0)** (2022-11-29) 
- **[cyberark/conjur-openapi-spec v5.3.0](https://github.com/cyberark/conjur-openapi-spec/releases/tag/v5.3.0)** (2021-12-22) 
- **[cyberark/conjur-oss-helm-chart v2.0.5](https://github.com/cyberark/conjur-oss-helm-chart/releases/tag/v2.0.5)** (2022-08-17)  …
=> Release v1.19.0+suite.1

CHANGELOG.md, suite.yml
Release v1.19.2 suite.1
Updated versions in `suite.yml`
N/A
*At least 1 todo must be completed in the sections below for the PR to be
merged.*
CHANGELOG update
changes, or
=> Release v1.19.2+suite.1

CHANGELOG.md, suite.yml
Release v1.19.3+suite.1
Updated `suite.yml` and `CHANGELOG.md`
CNJR-1095
*At least 1 todo must be completed in the sections below for the PR to be
merged.*
CHANGELOG update
changes, or
=> Release v1.19.3+suite.1
