cyberark/conjur-oss-suite-release

.codeclimate.yml
cmd/changelog-parser/main.go
pkg/template/template.go
templates/templates_test.go
templates/testdata/CHANGELOG_unified.md
templates/testdata/RELEASE_NOTES_unified.md

This change adds tests for our templates to ensure that
they output the exact structure of the data as we want.﻿

54 Add tests for template

---

README.md

This will give us visibility into test state which will help identify
problems earlier.

Added a GitHub actions unit test results to README

---

.github/workflows/test.yml
CONTRIBUTING.md
README.md
cmd/changelog-parser/main.go
cmd/changelog-parser/main_test.go
cmd/changelog-parser/testdata/expected_changelog_output.txt
cmd/changelog-parser/testdata/expected_release_output.txt
cmd/changelog-parser/testdata/repositories.yml

This PR adds integration tests to the suite so that we can be
sure that the in-repo E2E workflow from repositories.yml to the
output file generation is correct using the real data.﻿

56 Add integration tests

---

cmd/changelog-parser/main.go
pkg/github/github.go
pkg/github/github_test.go
pkg/repositories/repositories.go
pkg/repositories/repositories_test.go
pkg/repositories/testdata/repositories.yml

Since this code doesn't need to be in main, it is now both located in
the right place and has tests around its functionality.

Moved some methods from `main` to `pkg/<name>` package and added tests

---

cmd/changelog-parser/main.go
pkg/repositories/repositories.go
pkg/repositories/repositories_test.go
pkg/version/version.go
pkg/version/version_test.go
repositories.yml
templates/UNRELEASED_CHANGES_unified.md.tmpl
templates/templates_test.go
templates/testdata/RELEASE_NOTES_unified.md
templates/testdata/UNRELEASED_CHANGES_unified.md

This PR:
- Adds CLI option to generate "unreleased changes" report
- Improves template tests
- Improves version ranging error checking
- Fixed invalid value in `repositories.yml`

3 Add ability to generate document of unreleased changes

---

.github/workflows/release-publish-suite-commit.yml
suite.yml

This PR:
- Adds auto-committing of suite release file 
- Fixes issues with suite.yml

83 auto commit suite file

---

.github/workflows/update-wiki.yml

Closes #78
~**NOTE** that I commented out the components that do not have releases and so result in an error when generating unreleased changes.~

Generate a daily wiki page of unreleased changes since last suite release

---

release-testing/executors.sh
release-testing/go.mod
release-testing/go.sum
release-testing/init_store.go
release-testing/kv/client.go
release-testing/kv/cmd/main.go
release-testing/kv/store.go
release-testing/policy.yml.sh
release-testing/prepare.sh
release-testing/secretless_test.go
release-testing/store-component-versions.go
release-testing/store.sh
release-testing/test
suite.yml

Close #103 
Component versions are taken from the root level suite.yml. These are taken to reflect the release under consideration.

Release tests ingest component versions from suite.yml

---

pkg/version/version.go
pkg/version/version_test.go

This functionality adds the capability to return the filename of the
latest (highest semver) release files from a directory containing
multiple release YAMLs. This code is not supposed to be integrated in
the rest of the app yet.
Connected to #119

119 Added a method for finding the highest release file in a directory

---

.github/workflows/draft-release.yml

- Added step for generating ConjurSuite.htm
- Added step for uploading ConjurSuite.htm to release
- Added step for attaching suite.yml, ConjurSuite.htm, and CHANGELOG.md to release artifacts

117 - Suite Release Draft Includes Artifacts

---

pkg/cli/cli.go
pkg/cli/testdata/expected_suite_diff_output.txt
pkg/github/github.go
pkg/github/github_test.go
pkg/github/testdata/new_suite.yml
pkg/github/testdata/old_suite.yml
pkg/github/testdata/simple_changelog.md
pkg/http/http.go

- Drop changelog notes for repos that have not changed between the current and present suite
- Unit tests added for pkg/github.CollectComponents (#137)
- Helper methods created un github_test.go for certain reused blocks of code

#132 - Do not include change notes for unchanged versions

---

pkg/cli/testdata/expected_docs-release_diff_output.txt
pkg/cli/testdata/expected_docs-release_output.txt
templates/RELEASE_NOTES_unified.htm.tmpl
templates/testdata/RELEASE_NOTES_unified.htm

Made minor modifications to the HTML template to revise the language per recommendations from the TWs.

Minor updates to language in HTML template

---

suite.yml

Update the suite.yml to add the GCP marketplace tool for deploying Conjur OSS to GKE.

Add GCP marketplace integration to suite.yml

---

CONTRIBUTING.md
README.md

Resolves #160 
Resolves #159 
Updates the README with info about the purpose of the project and its versioning scheme, and adds utility usage info and detailed versioning instructions to CONTRIBUTING.

Update the README and CONTRIBUTING guide to prepare for first release

---

.gitignore
release-testing/prepare.sh
suite.yml

The suite.yml is updated to prepare for v1.10.0+suite.1 release.
TODO checklist:
Resolves #187

Suite updates for v1.10.0+suite.1 release

---

.github/workflows/draft-release.yml
.github/workflows/e2e-tests.yml
.github/workflows/unit-tests.yml
.gitignore
CHANGELOG.md
CONTRIBUTING.md
go.mod
k8s-ci/Dockerfile
pkg/github/github_test.go
pkg/http/http_test.go

- Bump Go version to 1.15
- Adds CHANGELOG to project, to track internal project changes.
Resolves #196

Fix broken tests

---

CHANGELOG.md
suite.yml

PR to prep for the January OSS suite release
Outstanding issues/PRs:
Release page: https://github.com/cyberark/conjur-oss-suite-release/wiki/v1.11.1-suite.2
Draft release notes: https://gist.github.com/izgeri/2a3e73f6f9b8c3ba9d7aa1233f1fa191
Open questions / issues:
- In the last release we announced we'd be dropping support for OpenShift 3.9 / 3.10 in this release - those changes are not already released in the suite components, so do we still want to announce it here?
- We will announce this in the next suite release, along with the new support for OCP 4.3 / 4.5
- cyberark/conjur-docs#1015 - issue to update the Ansible docs should be completed with this suite release. Updated content has been appended to the issue.
- Will be added to the docs issue with the draft release notes.
n/a
**If …

Update suite.yml for v1.11.1+suite.2 release

---

.github/workflows/e2e-tests.yml
k8s-ci/Dockerfile

This resolves an issue with helm not properly detecting the 'lookup' plugin
This resolves an issue with helm not properly detecting the 'lookup' plugin
Resolves #207 
```
-t release
```

Bump Helm Version in Test to 3.2.0

---

CHANGELOG.md
suite.yml

Bump suite to v1.11.2+suite.1
Link to gist with draft "What's New" content: https://gist.github.com/izgeri/200953d0792713a3f07c50af229d8e6f
~There is a known bug in #208 that is impacting the release notes that are generated with this release.~
n/a
```
-v v1.11.2+suite.1 \
-t release \
-o drafts/RELEASE_NOTES.md
```

Prepare for v1.11.2+suite.1 suite release

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
pkg/github/github.go
pkg/github/github_test.go
pkg/github/testdata/main_branch_changelog.md
pkg/github/testdata/main_v3.json
pkg/github/testdata/new_main_suite.yml
pkg/github/testdata/old_main_suite.yml
suite.yml

In this suite release, the Conjur OpenAPI specification is added to the suite.
- [Wiki page](https://github.com/cyberark/conjur-oss-suite-release/wiki/v1.11.6-suite.1)
- [Draft release notes](https://gist.github.com/izgeri/eaffdff86d7505e640490c2eef28628b)
Draft What's new content:
---
This Suite release aligns with Conjur Server [version 1.11.6](https://github.com/cyberark/conjur/releases/tag/v1.11.6). 
It includes the first linked release of the **Community Level** [Conjur OpenAPI v3 specification](https://github.com/cyberark/conjur-openapi-spec) with the Conjur server. The Conjur OpenAPI specification is an evolving project which provides a standardized, machine-readable version of the API that can be used to automatically generate API documentation, to generate Conjur client libraries …

Prepare for v1.11.6+suite.1 release

---

CONTRIBUTING.md

Our process has evolved slightly from when we first wrote this doc. In this commit,
I've updated the process to describe what we currently do.
n/a
```
-t release \
```

Update the suite release process

---

.github/workflows/e2e-tests.yml

- _What's changed? Why were these changes made?_
- _How should the reviewer approach this PR, especially if manual tests are required?_
- _Are there relevant screenshots you can add to the PR description?_
Resolves #[relevant GitHub issues, eg 76]
```
-t release \
```

Increase E2E test Conjur deployment timeout

---

go.mod
go.sum
release-testing/go.mod
release-testing/go.sum

Signed-off-by: Andy Tinkham <andy.tinkham@cyberark.com>
Remove all dependencies on gopkg.in/yaml.v2 versions before 2.4.0
Upgrades testify to 1.7.0
*At least 1 todo must be completed in the sections below for the PR to be
merged.*
CHANGELOG update
changes, or

Upgrade testify
